#!/usr/bin/env python3
"""Build the Boneheadz cosmetics manifest + resized web assets from Cam's layer library.

Re-run whenever Cam ships new art:
  python3 scripts/build-cosmetics.py "/path/to/BONEHEADZ NFT LIBRARY"

Deterministic: same input files -> same ids, names, and rarities, so player
inventories stay valid across art updates (ids are the source filenames).
"""
import hashlib
import json
import os
import sys
from PIL import Image

LIB = sys.argv[1] if len(sys.argv) > 1 else '/Users/tommiller/Documents/TALLY APP /BONEHEADZ NFT LIBRARY'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_ASSETS = os.path.join(ROOT, 'assets', 'bh')
OUT_DATA = os.path.join(ROOT, 'data', 'boneheadz.js')
SIZE = 640

# slot code -> (label, z-order, default item id or None)
SLOTS = {
    'BG': ('Background', 0, None),
    'B':  ('Body', 10, 'B0-1'),
    'S':  ('Socks', 20, None),
    'FW': ('Kicks', 30, None),
    'U':  ('Undies', 40, None),
    'P':  ('Pants', 50, None),
    'T':  ('Top', 60, None),
    'SK': ('Skull', 70, 'SK0-1'),
    'E':  ('Eyes', 80, None),
    'G':  ('Grillz', 90, None),
    'M':  ('Mouth', 100, None),
    'H':  ('Hat', 110, None),
    'IL': ('Left hand', 120, None),
    'IR': ('Right hand', 130, None),
    'C':  ('Pet', 5, None),  # companion sits BEHIND the character (just above BG)
    'YD': ('Yard', 150, None),  # anchored decor, not a full-frame layer
}

# Hand-curated items whose art lives outside the layer library.
SPECIALS = [
    {'id': 'YD1', 'slot': 'YD', 'file': 'assets/brand/tombstone.png', 'name': 'Haunted Tombstone', 'rarity': 'uncommon'},
    {'id': 'YD2', 'slot': 'YD', 'file': 'assets/brand/tomb.png', 'name': 'Tomb Gate', 'rarity': 'epic'},
]

RARITY_ORDER = ['common', 'uncommon', 'rare', 'epic', 'legendary']
# deterministic weights (must sum to 100)
RARITY_WEIGHTS = [52, 26, 13, 6, 3]

ADJ = {
    'common':    ['Basic', 'Street', 'Everyday', 'Standard', 'Corner-store'],
    'uncommon':  ['Fresh', 'Slick', 'Tidy', 'Sharp', 'Custom'],
    'rare':      ['Radical', 'Voltage', 'Turbo', 'Prime', 'Deluxe'],
    'epic':      ['Haunted', 'Molten', 'Cosmic', 'Royal', 'Storm-forged'],
    'legendary': ['Mythic', 'Eternal', 'Grandmaster', 'Celestial', 'Ancient'],
}
NOUN = {
    'BG': 'Backdrop', 'B': 'Bones', 'S': 'Socks', 'FW': 'Kicks', 'U': 'Undies',
    'P': 'Pants', 'T': 'Top', 'SK': 'Skull', 'E': 'Eyes', 'G': 'Grillz',
    'M': 'Chew', 'H': 'Hat', 'IL': 'Off-hand', 'IR': 'Main-hand', 'C': 'Pet',
}


def h32(s):
    return int(hashlib.sha256(s.encode()).hexdigest()[:8], 16)


def pick_rarity(item_id):
    r = h32('rarity:' + item_id) % 100
    acc = 0
    for name, w in zip(RARITY_ORDER, RARITY_WEIGHTS):
        acc += w
        if r < acc:
            return name
    return 'common'


def main():
    items = []
    for code in SLOTS:
        src = os.path.join(LIB, code)
        if not os.path.isdir(src):
            print(f'WARN: missing category {code}')
            continue
        os.makedirs(os.path.join(OUT_ASSETS, code), exist_ok=True)
        files = sorted(f for f in os.listdir(src) if f.lower().endswith('.png'))
        slot_items = []
        for f in files:
            item_id = f[:-4]
            im = Image.open(os.path.join(src, f)).convert('RGBA')
            im = im.resize((SIZE, SIZE), Image.LANCZOS)
            im.save(os.path.join(OUT_ASSETS, code, f), optimize=True)
            rarity = pick_rarity(item_id)
            slot_items.append({'id': item_id, 'slot': code, 'rarity': rarity})
        # guarantee the top of every slot has something to chase
        if slot_items:
            if not any(i['rarity'] == 'legendary' for i in slot_items):
                slot_items[h32('leg:' + code) % len(slot_items)]['rarity'] = 'legendary'
            if not any(i['rarity'] == 'epic' for i in slot_items):
                slot_items[h32('epic:' + code) % len(slot_items)]['rarity'] = 'epic'
        items.extend(slot_items)

    # names: deterministic adjective + slot noun + running number within slot
    counter = {}
    for it in items:
        n = counter.get(it['slot'], 0) + 1
        counter[it['slot']] = n
        adj = ADJ[it['rarity']][h32('adj:' + it['id']) % len(ADJ[it['rarity']])]
        it['name'] = f"{adj} {NOUN[it['slot']]} #{n}"

    # defaults are always owned and never drop from crates
    defaults = [d for (_, _, d) in SLOTS.values() if d]
    for it in items:
        if it['id'] in defaults:
            it['rarity'] = 'common'
            it['default'] = True

    items.extend(SPECIALS)

    slots_out = [{'code': c, 'label': l, 'z': z, 'default': d} for c, (l, z, d) in SLOTS.items()]
    body = (
        '// GENERATED by scripts/build-cosmetics.py from Cam\'s Boneheadz library. Do not hand-edit.\n'
        '// Placeholder art: re-run the script when final art lands (ids stay stable).\n'
        f'export const BH_SLOTS = {json.dumps(slots_out, indent=1)};\n\n'
        f'export const BH_ITEMS = {json.dumps(items, indent=1)};\n\n'
        'export const BH_BY_ID = Object.fromEntries(BH_ITEMS.map(i => [i.id, i]));\n'
        'export function bhAsset(item) { return item.file || `assets/bh/${item.slot}/${item.id}.png`; }\n'
    )
    with open(OUT_DATA, 'w') as fh:
        fh.write(body)

    from collections import Counter
    rc = Counter(i['rarity'] for i in items)
    print(f'{len(items)} items -> {OUT_DATA}')
    print('rarity spread:', dict(rc))
    total = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(OUT_ASSETS) for f in fs)
    print(f'assets: {total/1e6:.1f} MB at {SIZE}px')


if __name__ == '__main__':
    main()
